<script setup>
import { computed, onMounted, ref } from 'vue'
import VehicleCard from './VehicleCard.vue'
import { fleet as fallbackFleet } from '@/data/site'
import { tr } from '@/i18n'

/**
 * Renders the fleet from `/data/vehicles.json`.
 *
 * The manifest is generated by `scripts/scan-assets.mjs` from the files in
 * `public/images/vehicles/`, so any new photo dropped into that folder is
 * picked up automatically. If the manifest is missing or a photo has not been
 * described yet, we fall back to the curated list in `src/data/site.js` so the
 * page is never empty.
 *
 * The manifest is fetched at run time, which means it arrives in English —
 * nothing has translated it, because it did not exist when the data modules
 * were evaluated. `tr()` runs over whatever comes back, using the same
 * catalogue the rest of the site uses; `scripts/extract-i18n.mjs` reads the
 * manifest too, so its copy is a first-class part of `en.json`.
 */
const props = defineProps({
  limit: { type: Number, default: 0 },
  /** Only these slugs, in this exact order. */
  slugs: { type: Array, default: () => [] },
  /** Hide these slugs (the counterpart of `slugs`). */
  exclude: { type: Array, default: () => [] },
})

const vehicles = ref(fallbackFleet)
const loaded = ref(false)

onMounted(async () => {
  try {
    const res = await fetch(`${import.meta.env.BASE_URL || '/'}data/vehicles.json`.replace('//data', '/data'), {
      cache: 'no-cache',
    })
    if (res.ok) {
      const json = await res.json()
      const list = Array.isArray(json) ? json : (json?.items ?? [])
      if (list.length) vehicles.value = tr(list)
    }
  } catch {
    /* keep the fallback list */
  } finally {
    loaded.value = true
  }
})

const shown = computed(() => {
  let list = vehicles.value

  if (props.slugs.length) {
    // follow the caller's order rather than whatever order the manifest uses
    const bySlug = new Map(list.map((v) => [v.slug, v]))
    list = props.slugs.map((s) => bySlug.get(s)).filter(Boolean)
  } else if (props.exclude.length) {
    list = list.filter((v) => !props.exclude.includes(v.slug))
  }

  return props.limit ? list.slice(0, props.limit) : list
})
</script>

<template>
  <div class="grid grid--3">
    <VehicleCard v-for="v in shown" :key="v.slug || v.name" :vehicle="v" />
  </div>
</template>
