/**
 * Rebuild `src/i18n/locales/en.json` from the source, and report how much of
 * the catalogue each translation has covered.
 *
 * `en.json` is generated, never hand-edited: the English sentence IS the
 * message key (see `src/i18n/index.js`), so the only way the catalogue can stay
 * honest is to derive it from the code that renders the copy.
 *
 * Two sources feed it:
 *   1. every string leaf in the exported data structures (`src/data/*.js`),
 *      collected by importing them with `setPassThrough(true)` so `tr()` hands
 *      back the raw English;
 *   2. every literal passed to `t()` anywhere in `src/`.
 *
 * Technical strings — slugs, file paths, URLs, e-mails, hex colours, currency
 * codes — are filtered out. They do not need translating, and leaving them in
 * would invite a translator to "translate" a route path.
 *
 * Run:  npm run i18n
 * Also runs as the first step of `npm run build`, so a new string can never be
 * missing from the catalogue.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'
import { pathToFileURL } from 'node:url'

const ROOT = process.cwd()
const LOCALES_DIR = join(ROOT, 'src', 'i18n', 'locales')
const SRC = join(ROOT, 'src')
const CODES = ['en', 'fr', 'es', 'it', 'de']

/* ---------------------------------------------------------------- filters */

/** Values that look like code, not copy. */
function looksTechnical(value) {
  const v = value
  if (v.length < 2) return true
  if (!/[A-Za-z]/.test(v)) return true
  if (/^https?:|^mailto:|^tel:|^wa\.me/.test(v)) return true
  if (v.includes('@') && !v.includes(' ')) return true
  if (/^[#&][0-9a-fA-F]{3,8}$/.test(v)) return true
  if (/^[a-z0-9]+(?:[-_./][a-z0-9]+)+$/.test(v)) return true // slugs & paths
  if (v.startsWith('/')) return true
  if (/^[\d\s.,:%+–—-]+$/.test(v)) return true // "1–3", "24 / 7", "$1.50 per km"
  if (/\.(jpe?g|png|svg|webp|mp4|json|html|xml)$/i.test(v)) return true
  if (/^[a-z][a-z0-9]*$/.test(v)) return true // bare lowercase token: "hongqi"
  if (/^[A-Z]{2,4}$/.test(v)) return true // currency / icon codes: "USD", "MPV"
  if (/^[\w-]+\.(com|cn|net|org)$/i.test(v)) return true
  if (v.includes('${')) return true
  return false
}

/** Exact values that pass the checks above but carry no copy. */
const IGNORE = new Set(['CantonPickup', 'Guangzhou', 'Foshan', 'Shenzhen', 'China'])

function isCopy(value) {
  if (typeof value !== 'string') return false
  const v = value.replace(/\s+/g, ' ').trim()
  if (!v || IGNORE.has(v) || looksTechnical(v)) return false
  return true
}

/* ------------------------------------------------------ data-module walk */

function walk(value, out) {
  if (typeof value === 'string') {
    if (isCopy(value)) out.add(value.replace(/\s+/g, ' ').trim())
    return
  }
  if (Array.isArray(value)) {
    for (const item of value) walk(item, out)
    return
  }
  if (value && typeof value === 'object') {
    for (const key of Object.keys(value)) walk(value[key], out)
  }
}

/**
 * Exports that stay English on purpose.
 *
 * The guides under /blog and the two legal documents are long-form reading,
 * not interface copy: their wording is a liability if it is machine-translated
 * (the privacy policy names a data controller and a governing law), and they
 * are read once by a visitor who is already committed. They keep their English
 * text; everything else on the site is translated.
 */
const SKIP_EXPORTS = new Set(['privacySections', 'termsSections'])
const SKIP_FILES = new Set(['articles.js'])

async function collectFromData() {
  const i18n = await import(pathToFileURL(join(SRC, 'i18n', 'index.js')).href)
  i18n.setPassThrough(true)

  const files = (await readdir(join(SRC, 'data'))).filter(
    (f) => f.endsWith('.js') && !SKIP_FILES.has(f),
  )
  const out = new Set()
  for (const file of files.sort()) {
    const mod = await import(pathToFileURL(join(SRC, 'data', file)).href)
    for (const [name, value] of Object.entries(mod)) {
      if (typeof value === 'function' || SKIP_EXPORTS.has(name)) continue
      walk(value, out)
    }
    console.log(`  data/${file}`)
  }
  return out
}

/* ------------------------------------------------- run-time manifest copy */

/**
 * Copy that only exists in a JSON manifest fetched by the browser.
 *
 * `public/data/vehicles.json` and `public/data/videos.json` carry the vehicle
 * blurbs and the clip titles. They are fetched after the app boots, so `tr()`
 * has to be applied to whatever comes back — and for that to do anything the
 * strings have to be in the catalogue, which means reading the manifests here.
 *
 * Only the copy fields are read. `slug`, `image`, `src`, `poster` and `url` are
 * code: translating a path produces a 404.
 *
 * (The manifests are regenerated by `scan-assets.mjs` later in the build, so
 * this reads the copy that is already on disk. A brand-new photo therefore
 * needs one build before its blurb reaches the catalogue — same as any other
 * new copy, which needs `npm run i18n`.)
 */
const MANIFESTS = [
  { file: 'vehicles.json', text: ['models', 'passengers', 'luggage', 'tag', 'description'], list: ['features'] },
  { file: 'videos.json', text: ['title', 'caption'], list: [] },
  // The customer's own name is left alone; everything else on a review card is
  // copy — the quote, the service it was for, the month, and the alt text that
  // describes the screenshot to somebody who cannot see it.
  { file: 'reviews.json', text: ['text', 'service', 'date', 'alt'], list: [] },
]

async function collectFromManifests() {
  const out = new Set()
  for (const def of MANIFESTS) {
    const path = join(ROOT, 'public', 'data', def.file)
    let json
    try {
      json = JSON.parse(await readFile(path, 'utf8'))
    } catch {
      console.log(`  (no public/data/${def.file} yet)`)
      continue
    }
    const items = Array.isArray(json) ? json : (json?.items ?? [])
    for (const item of items) {
      for (const key of def.text) walk(item[key], out)
      for (const key of def.list) walk(item[key], out)
    }
    console.log(`  public/data/${def.file} (${items.length} item(s))`)
  }
  return out
}

/**
 * Strings the scanner cannot see: prop defaults.
 *
 * `<script setup>` hoists a prop's `default:` to module scope, so it is
 * evaluated before `t()` exists — `default: t('Videos')` throws
 * `ReferenceError` during prerender. The components therefore keep the English
 * literal as the default and translate at the render site (`{{ t(title) }}`),
 * which means the source only ever contains the bare string. The scanner sees
 * no `t()` call and the key would be pruned from the catalogue.
 *
 * Listed here by hand so they survive. `checkPropDefaults()` below prints a
 * warning if a prop default shows up that is missing from this list, so a new
 * one cannot slip through unnoticed.
 */
const MANUAL_KEYS = [
  'Get Your Free Quote',
  'Tell us the trip and we will come back with a fixed, all-inclusive price.',
  'Videos',
  'We accept:',
]

/* ----------------------------------------------------- t() call scanner */

async function sourceFiles(dir) {
  const found = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'i18n') continue
      found.push(...(await sourceFiles(full)))
    } else if (/\.(vue|js)$/.test(entry.name)) {
      found.push(full)
    }
  }
  return found
}

/**
 * Vue's template compiler decodes HTML entities inside a text node before the
 * expression ever runs, so `t('Vehicles &amp; Pricing')` hands `t()` the string
 * `Vehicles & Pricing`. The catalogue has to hold what `t()` actually receives,
 * or the lookup misses and the English is rendered verbatim — which is exactly
 * what happened to ten headings on the first pass.
 */
const ENTITIES = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'", '&nbsp;': ' ' }
const decodeEntities = (s) => s.replace(/&(?:amp|lt|gt|quot|nbsp|#39);/g, (m) => ENTITIES[m])

async function collectFromCalls() {
  const out = new Set()
  const backtick = []
  for (const file of (await sourceFiles(SRC)).sort()) {
    const text = await readFile(file, 'utf8')
    const re = /(?<![\w$.])t\(\s*(?:'((?:[^'\\\n]|\\.)*)'|"((?:[^"\\\n]|\\.)*)")/g
    for (const m of text.matchAll(re)) {
      const raw = m[1] ?? m[2]
      if (!raw) continue
      const value = decodeEntities(raw.replace(/\\(['"\\])/g, '$1')).replace(/\s+/g, ' ').trim()
      if (value) out.add(value)
    }
    for (const m of text.matchAll(/(?<![\w$.])t\(\s*`[^`]*\$\{/g)) {
      backtick.push(relative(ROOT, file))
    }
  }
  if (backtick.length) {
    console.log(`  WARNING ${backtick.length} t() call(s) use a template literal — use {param} placeholders instead`)
  }
  return out
}

/**
 * Every prop default that is not already in the catalogue is reported. Most
 * are numbers, booleans or class names and the warning is noise, but a piece
 * of copy hiding in a default is otherwise invisible — `t()` is called on it
 * at render time and silently renders English.
 */
async function checkPropDefaults(known) {
  const suspects = []
  for (const file of (await sourceFiles(SRC)).sort()) {
    if (!file.endsWith('.vue')) continue
    const text = await readFile(file, 'utf8')
    for (const m of text.matchAll(/default:\s*(?:'((?:[^'\\\n]|\\.)*)'|"((?:[^"\\\n]|\\.)*)")/g)) {
      const value = decodeEntities((m[1] ?? m[2] ?? '').replace(/\\(['"\\])/g, '$1')).trim()
      if (!value || known.has(value)) continue
      // Skip the noise: paths, urls, class names, single-word identifiers,
      // hex colours. What is left should be a sentence — or a false positive
      // worth looking at.
      if (/^[a-z0-9-]+$/.test(value)) continue // kebab-case identifier / slug
      if (/^[/#.]/.test(value)) continue // path, anchor, selector
      if (/^(?:https?:|data:|\/)/.test(value)) continue
      if (/^#[0-9a-f]{3,8}$/i.test(value)) continue
      suspects.push(`${relative(ROOT, file)}: ${JSON.stringify(value)}`)
    }
  }
  return suspects
}

/* ------------------------------------------------------------------ main */

console.log('extract-i18n: reading data modules')
const fromData = await collectFromData()

console.log('extract-i18n: reading run-time manifests')
const fromManifests = await collectFromManifests()

console.log('extract-i18n: scanning t() calls')
const fromCalls = await collectFromCalls()

const catalogue = [
  ...new Set([...fromData, ...fromManifests, ...fromCalls, ...MANUAL_KEYS]),
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))

const orphans = await checkPropDefaults(new Set(catalogue))
if (orphans.length) {
  console.log(
    `extract-i18n: ${orphans.length} prop default(s) are not in the catalogue` +
      ` (add to MANUAL_KEYS if any is copy):`,
  )
  for (const o of orphans.slice(0, 20)) console.log(`      ${o}`)
}

const en = {}
for (const key of catalogue) en[key] = key

await writeFile(join(LOCALES_DIR, 'en.json'), JSON.stringify(en, null, 2) + '\n', 'utf8')

const PLACEHOLDER = /\{(\w+)\}/g
const placeholders = (s) => [...s.matchAll(PLACEHOLDER)].map((m) => m[1]).sort().join(',')

let missingTotal = 0
let problemTotal = 0
for (const code of CODES) {
  if (code === 'en') continue
  const path = join(LOCALES_DIR, `${code}.json`)
  let bundle = {}
  let parseError = ''
  try {
    bundle = JSON.parse(await readFile(path, 'utf8'))
  } catch (err) {
    parseError = err.message
  }
  if (parseError) {
    console.log(`  ${code}: INVALID JSON — ${parseError}`)
    problemTotal += 1
    continue
  }
  // Keep any translation whose key no longer exists at the bottom of the file
  // instead of deleting it — the English may come back.
  const missing = catalogue.filter((k) => !bundle[k])
  missingTotal += missing.length
  const stale = Object.keys(bundle).filter((k) => !en[k])
  // A dropped `{city}` silently prints the literal braces to the visitor.
  const broken = catalogue.filter(
    (k) => bundle[k] && placeholders(k) !== placeholders(bundle[k]),
  )
  problemTotal += broken.length
  console.log(
    `  ${code}: ${catalogue.length - missing.length}/${catalogue.length} translated` +
      (broken.length ? `, ${broken.length} PLACEHOLDER MISMATCH` : '') +
      (stale.length ? `, ${stale.length} unused key(s) kept` : ''),
  )
  for (const k of broken.slice(0, 5)) {
    console.log(`      ${JSON.stringify(k).slice(0, 70)} -> ${JSON.stringify(bundle[k]).slice(0, 70)}`)
  }
}

console.log(`extract-i18n: en.json holds ${catalogue.length} messages`)
if (missingTotal) console.log(`extract-i18n: ${missingTotal} untranslated message(s) will fall back to English`)
if (problemTotal) console.log(`extract-i18n: ${problemTotal} problem(s) need attention`)

